### ISSUE TITLE
java.lang.NoClassDefFoundError: com/microsoft/aad/msal4j/ClientCredentialFactory

### ISSUE THREAD

**Issue by ermidev** [Azure/azure-kusto-spark#212] opened 2021-11-28 02:36 UTC
**Describe the bug**
Fail to write to Kusto (Azure Data Explore), on Spark Stream. Throwing the following exception.
```
java.lang.NoClassDefFoundError: com/microsoft/aad/msal4j/ClientCredentialFactory
	at com.microsoft.azure.kusto.data.auth.TokenProviderFactory.createTokenProvider(TokenProviderFactory.java:25)
	at com.microsoft.azure.kusto.data.ClientImpl.<init>(ClientImpl.java:53)
	at com.microsoft.azure.kusto.data.ClientFactory.createClient(ClientFactory.java:16)
	at com.microsoft.kusto.spark.utils.KustoClient.engineClient$lzycompute(KustoClient.scala:34)
	at com.microsoft.kusto.spark.utils.KustoClient.engineClient(KustoClient.scala:34)
	at com.microsoft.kusto.spark.datasink.KustoWriter$.write(KustoWriter.scala:65)
	at com.microsoft.kusto.spark.datasink.KustoSink.addBatch(KustoSink.scala:26)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:537)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:89)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:141)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:79)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:535)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:534)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:198)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:166)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:160)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193)
```
**To Reproduce**
Using the following code snippet. 
```
    data
      .writeStream
      .format("com.microsoft.kusto.spark.datasink.KustoSinkProvider")
      .option(KustoSinkOptions.KUSTO_CLUSTER, "xyz.westus2")
      .option(KustoSinkOptions.KUSTO_DATABASE, "db_sample")
      .option(KustoSinkOptions.KUSTO_TABLE, "Sample")
      .option(KustoSinkOptions.KUSTO_AAD_APP_ID, "1234-xxxx")
      .option(KustoSinkOptions.KUSTO_AAD_APP_SECRET, aadSecret)
      .option("checkpointLocation", s"${adlsRoot}/data/checkpoint/sample")
      .trigger(Trigger.ProcessingTime(10000))
      .start()
```

** Installed Maven Packages *** 
```
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>msal4j</artifactId>
            <version>1.11.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>adal4j</artifactId>
            <version>1.6.2</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure.kusto</groupId>
            <artifactId>kusto-data</artifactId>
            <version>2.4.1</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure.kusto</groupId>
            <artifactId>kusto-ingest</artifactId>
            <version>2.4.1</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure.kusto</groupId>
            <artifactId>kusto-spark_2.4_2.11</artifactId>
            <version>2.4.1</version>
        </dependency>
```
**Expected behavior**
Is should successfully insert the data into Kusto database -- according to this read me https://github.com/Azure/azure-sqldb-spark#readme 

** Running Environment **
Azure Synapse, using SparkPool, with maven-shade package created for the Spark-Stream job jar file.

**Additional context**

Spark Version: 2.4
Scala Version: 2.11

**Comment by yihezkel** [comment] 2021-11-30 09:31
Hi @ermidev ,

There's apparently an msal4j dependency conflict. The latest version of the Spark Connector includes msal4j version 1.9.1, and you have version 1.11.0. It seems you have a dependency that also includes msal4j, which can be resolved via explicit dependency management.

To understand the root cause better, please execute `mvn dependency:tree` and include the output.

Thanks!

**Comment by artmasa** [comment] 2021-12-02 15:16
I'm facing the same exception on a Synapse cluster. I'm not specifying any dependencies.

**Comment by yihezkel** [comment] 2021-12-04 20:52
What's the output of `mvn dependency:tree`?

**Comment by ohadbitt** [comment] 2021-12-19 09:09
Hi 
@ermidev : If you are using maven you dont need to import kust-data and kusto-ingest - this can only lead to such cases where you dont know which versions to take - as the versions don't always go by the same name. If you must provide specific version for the kusto-data and kusto-ingest - look for the relevant version tag in this repo and take the versions from the pom file.
@artmasa: please provide more details - do you mean Spark Synapse environment or are you using this connector to interact with a kusto synapse cluster?

**Comment by yihezkel** [comment] 2022-01-16 20:15
Closing, as we haven't heard back with the requested information necessary to help resolve your issue.

Please feel free to reopen with that information.

**Closed by yihezkel** 2022-01-16 20:15 UTC
